In [74]:
import pandas as pd

In [75]:
data = pd.read_csv('dataset.csv')

In [76]:
data.head()

Location_Easting_OSGR  Location_Northing_OSGR  Longitude   Latitude  \
0                 525130                  180050  -0.198465  51.505538   
1                 526530                  178560  -0.178838  51.491836   
2                 524610                  181080  -0.205590  51.514910   
3                 524420                  181080  -0.208327  51.514952   
4                 524630                  179040  -0.206022  51.496572   

   Accident_Severity  Number_of_Vehicles  Number_of_Casualties        Date  \
0                  3                   1                     1  12/01/2015   
1                  3                   1                     1  12/01/2015   
2                  3                   1                     1  12/01/2015   
3                  3                   1                     1  13/01/2015   
4                  2                   2                     1  09/01/2015   

   Day_of_Week   Time  ...  Junction_Control 2nd_Road_Class  2nd_Road_Number  \
0            2  18:45  ...               4.0            6.0              0.0   
1            2  07:50  ...               4.0            3.0           3218.0   
2            2  18:08  ...               4.0            6.0              0.0   
3            3  07:40  ...               4.0            6.0              0.0   
4            6  07:30  ...               2.0            3.0           3220.0   

   Light_Conditions  Weather_Conditions  Road_Surface_Conditions  \
0                 4                   1                      1.0   
1                 1                   1                      1.0   
2                 4                   2                      2.0   
3                 1                   1                      2.0   
4                 1                   2                      2.0   

   Urban_or_Rural_Area  Casualty_Severity  Casualty_Type  Junction_Location  
0                    1                  3              0                8.0  
1                    1                  3              0                8.0  
2                    1                  3              0                2.0  
3                    1                  3              0                2.0  
4                    1                  2              1                8.0  

[5 rows x 27 columns]

In [77]:
relevant_cols = ['Light_Conditions', 'Day_of_Week', 'Urban_or_Rural_Area', 'Road_Surface_Conditions', 'Weather_Conditions']
casualties = ['Number_of_Casualties']

In [78]:
multivar_coefficients = []

corr_mat = data[relevant_cols + casualties].corr()
print(corr_mat[casualties[0]])
for h in corr_mat[casualties[0]]:
    print(h)

multivar_coefficients += list(
    map(
        lambda c: (list(c[0]), c[1]),
        zip(
            map(
                lambda c: (c, casualties[0]), 
                corr_mat.columns), 
        corr_mat[casualties[0]])))

Light_Conditions          -0.022702
Day_of_Week                0.075101
Urban_or_Rural_Area        0.145055
Road_Surface_Conditions    0.060878
Weather_Conditions         0.156439
Number_of_Casualties       1.000000
Name: Number_of_Casualties, dtype: float64
-0.0227020712209112
0.07510132850557351
0.14505478503862343
0.06087821007684398
0.1564391784384032
1.0


In [79]:
from itertools import combinations

perms = []
for i in range(2, len(relevant_cols)):
    perm = combinations(relevant_cols, i)
    perms += list(map(lambda p: list(p), perm))

In [83]:
import numpy as np

def multivar_coeff(corr_mat):
    upper = np.triu(corr_mat, k=1)
    print(upper)
    return np.sqrt(
        np.sum(upper**2) - 2*np.product(upper))


In [84]:

for perm in perms:
    
    variables = perm + casualties
    corr_mat = data[variables].corr().to_numpy()
    
    multivar_coefficients.append((variables, multivar_coeff(corr_mat)))

multivar_coefficients

[[ 1.          0.00464574 -0.02270207]
 [ 0.          1.          0.07510133]
 [ 0.          0.          1.        ]]
[[ 1.          0.04021755 -0.02270207]
 [ 0.          1.          0.14505479]
 [ 0.          0.          1.        ]]
[[ 1.          0.19299544 -0.02270207]
 [ 0.          1.          0.06087821]
 [ 0.          0.          1.        ]]
[[ 1.          0.1152659  -0.02270207]
 [ 0.          1.          0.15643918]
 [ 0.          0.          1.        ]]
[[ 1.00000000e+00 -8.96783007e-04  7.51013285e-02]
 [ 0.00000000e+00  1.00000000e+00  1.45054785e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.         -0.01742292  0.07510133]
 [ 0.          1.          0.06087821]
 [ 0.          0.          1.        ]]
[[1.         0.00842116 0.07510133]
 [0.         1.         0.15643918]
 [0.         0.         1.        ]]
[[1.         0.10396888 0.14505479]
 [0.         1.         0.06087821]
 [0.         0.         1.        ]]
[[1.         0.02713036 0.14505479]
 [

[(['Light_Conditions', 'Number_of_Casualties'], -0.0227020712209112),
 (['Day_of_Week', 'Number_of_Casualties'], 0.07510132850557351),
 (['Urban_or_Rural_Area', 'Number_of_Casualties'], 0.14505478503862343),
 (['Road_Surface_Conditions', 'Number_of_Casualties'], 0.06087821007684398),
 (['Weather_Conditions', 'Number_of_Casualties'], 0.1564391784384032),
 (['Number_of_Casualties', 'Number_of_Casualties'], 1.0),
 (['Light_Conditions', 'Day_of_Week', 'Number_of_Casualties'],
  1.7338330878393189),
 (['Light_Conditions', 'Urban_or_Rural_Area', 'Number_of_Casualties'],
  1.7387276170098624),
 (['Light_Conditions', 'Road_Surface_Conditions', 'Number_of_Casualties'],
  1.7439807281351523),
 (['Light_Conditions', 'Weather_Conditions', 'Number_of_Casualties'],
  1.7430647800872503),
 (['Day_of_Week', 'Urban_or_Rural_Area', 'Number_of_Casualties'],
  1.7397361594292582),
 (['Day_of_Week', 'Road_Surface_Conditions', 'Number_of_Casualties'],
  1.7348342641286716),
 (['Day_of_Week', 'Weather_Condit

In [82]:
multivar_coefficients

[(['Light_Conditions', 'Number_of_Casualties'], -0.0227020712209112),
 (['Day_of_Week', 'Number_of_Casualties'], 0.07510132850557351),
 (['Urban_or_Rural_Area', 'Number_of_Casualties'], 0.14505478503862343),
 (['Road_Surface_Conditions', 'Number_of_Casualties'], 0.06087821007684398),
 (['Weather_Conditions', 'Number_of_Casualties'], 0.1564391784384032),
 (['Number_of_Casualties', 'Number_of_Casualties'], 1.0),
 (['Light_Conditions', 'Day_of_Week', 'Number_of_Casualties'],
  1.7338330878393189),
 (['Light_Conditions', 'Urban_or_Rural_Area', 'Number_of_Casualties'],
  1.7387276170098624),
 (['Light_Conditions', 'Road_Surface_Conditions', 'Number_of_Casualties'],
  1.7439807281351523),
 (['Light_Conditions', 'Weather_Conditions', 'Number_of_Casualties'],
  1.7430647800872503),
 (['Day_of_Week', 'Urban_or_Rural_Area', 'Number_of_Casualties'],
  1.7397361594292582),
 (['Day_of_Week', 'Road_Surface_Conditions', 'Number_of_Casualties'],
  1.7348342641286716),
 (['Day_of_Week', 'Weather_Condit